### ISSUE TITLE
This library does not set a custom user agent

### ISSUE THREAD

**Issue by Ironholds** [kenpratt/wikipedia-client#26]
My ruby-fu is weak, but [this line](https://github.com/kenpratt/wikipedia-client/blob/e1fc61ad92294a67098259f41ae76b4a3f786dbf/lib/wikipedia/client.rb#L49) suggests the gem is just reporting as Ruby/version.

This is not compliant with our API etiquette guidelines or expectations. Please provide an informative default user agent that contains a URL to this project, and (for additional cookies) offer users the ability to append their own agent for their project-specific querying.

**Comment by matthin** [comment]
Now that #30 has been merged, I think this issue could be closed.
