### ISSUE TITLE
getting "undefined method 'find' for Wikipedia::Module" when running Wikipedia.find

### ISSUE THREAD

**Issue by ddd1600** [kenpratt/wikipedia-client#3]

**Comment by harman28** [comment]
@chr1831 If that were the issue, he'd be getting `NameError: uninitialized constant Wikipedia`, and not this.

**Comment by harman28** [comment]
Figured it out, adding this for future reference if someone else comes searching.
You need to add `gem 'wikipedia-client'` to your Gemfile, and not `gem 'wikipedia'`. I was adding the latter, which is a completely different gem!
