### ISSUE TITLE
Page.text not available in 1.4.0 gem.

### ISSUE THREAD

**Issue by dannytip** [kenpratt/wikipedia-client#33]
Page.text was added in this commit on May 3, 2014: https://github.com/kenpratt/wikipedia-client/commit/e3142c1b909cc87a57509ec8889a09b8beb8b7d1

Yet the 1.4.0 gem pushed to rubygems on June 25, 2015 doesn't include it. 

Is there a reason for this?

**Comment by pietromenna** [comment]
Thanks for letting us know about this problem @dannytip !

I just published the new version 1.5.0 which includes the fix to the problem and also includes some new features. 

The reason of the issue am I not sure, but I downloaded 1.4.0 and the code was not in sync!

**Comment by dannytip** [comment]
Awesome thanks @pietromenna
