### ISSUE TITLE
How to deal with the annoying SSL certificate error?

### ISSUE THREAD

**Issue by maurobio** [kenpratt/wikipedia-client#37]
I get this annoying error (using Ruby 2.0.0 from RubyInstaller under Windows 7):
"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)". There are lots of suggestions for how to fix this, but I could find none that worked for wikipedia-client. Any hints?

**Comment by pietromenna** [comment]
Hi @maurobio, I think this is not directly related to wikipedia-client, but it is a problem with the installation of Ruby which contains and missing/old certificate. Wikipedia-client uses OpenSSL to connect via HTTPS.
I can recommend you to check this [link] (https://groups.google.com/forum/#!topic/rubyinstaller/DVIDvs7xKC0/discussion) if you haven't looked into it.

**Comment by maurobio** [comment]
Hi @pietromenna, thanks for you reply. Before seeing your message, I solved the problem by adding the following lines at the beginning of my script:

require 'openssl'
$VERBOSE = nil
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE 

This works, but of course is not a very good solution because to disable ssl verification is not a very good idea. The solution pointed out in the link you provided seems more robust and I will try it.

Thanks!

**Comment by pietromenna** [comment]
Good! Let us know if it works!

**Comment by maurobio** [comment]
Unfortunately, it didn't. I followed the directions provided in the above link (copying the pem certificate file to the Ruby install dir, etc., to no effect. However, the workaround of disabling ssl verification works and is, at least, usable.

**Comment by pietromenna** [comment]
The problem is not related to wikipedia-client but to openssl.
