### ISSUE TITLE
Method for getting article summary

### ISSUE THREAD

**Issue by maurobio** [kenpratt/wikipedia-client#38]
A method for returning the summary of a Wikipedia article is badly needed.

**Comment by pietromenna** [comment]
Hey @maurobio , I would be more than happy to merge a Pull Request with this new feature! 

Don't forget to include the tests!

**Comment by maurobio** [comment]
@pietromenna: I consider myself a Ruby newbie and do not feel inclined to mess with the wikipedia-client library source code. However, a good example of what I suggest can be find in the wikipedia_wrapper gem (https://rubygems.org/gems/wikipedia_wrapper), which implements many of the same methods of wikipedia-client, plus one for extracting the article summary. Unfortunately, its author is not on GitHub.

**Comment by pietromenna** [comment]
I found the repository for wikipedia_wrapper. I think there are different ways to achieve the same results without copying code. I think we can try to write the tests for what we expect for a single article and work on it. If you don't mind I can try to help you. At least to write the tests for this new feature.

**Comment by maurobio** [comment]
@pietromenna I will attempt to create a workaround for grabing the summary from the page text returned by the respective method in wikipedia-client. Once it works, it will be possible to add the code as a new method. This solution does not involve any copying of code (and furthermore, I found the code of wikipedia_wrapper less than understandable).

**Comment by maurobio** [comment]
Here is a tentative function that returns the summary for a Wikipedia article passed as the first argument. It also accepts as optional arguments the maximum number of characters or sentences to be returned. Hope it can provide a useful basis for implementation in the wikipedia-client codebase.

def summary(text, characters: nil, sentences: nil)
    s = text.split(pattern="==")
    s = s[0].strip
    if characters
      s = s[0..characters].rpartition(" ").first << " ..."
    end
    if sentences
      text_arr = s.split(/[\.\!\?] +(?=[A-Z])/)
      text_arr = text_arr.first(sentences)
      s = text_arr.join(' ')
      last_ch = s[-1]
      if last_ch != '.'
        s = s + '.'
      end
    end
    return s  
end

**Comment by pietromenna** [comment]
Hey @maurobio , I just run some tests over the code you wrote! It works! 
What do you think if we do this way:
- In my fork repo, I will create a new branch and I will leave the code for the test suite (rspec). (Maybe this takes until Thursday)
- After it is ready, copy and create the same under your fork and include your code which will pass the tests.
- Send a PR closing this issue!
- You get the credits for the code :+1:  !!

**Comment by maurobio** [comment]
@pietromenna: We can do as you deem appropriate. Please notice that the code I provided is for an ordinary function, but for inclusion in the codebase it should be turned into a method of the main wikipedia-client class, so that it can be called as:

```Ruby
require 'wikipedia'
page = Wikipedia.find( 'Getting Things Done' )
page.text
page.summary(characters: 100) # Get the first 100 characters of the article summary
```
Cheers!

**Comment by pietromenna** [comment]
Hi @maurobio,

The new branch in my fork repo can be found [here](https://github.com/pietromenna/wikipedia-client/tree/page-summary-method). It contains a mocked test for the summary method.

It does not contain tests for the characters or sentences parameters you suggested. Feel free to add them!

Also I included the documentation in the README. Please, feel free to copy/adjust and send a PR! 

Thanks a lot for your suggestions and help so far!

**Comment by maurobio** [comment]
@pietromenna Thanks. I didn't understand why the characters and sentences parameters have not been included; they are necessary because for many Wikipedia articiels the summaries are quite long (and therefore need to be abridged).

I can add them to my own fork, but shouldn't we have a single gem file to publish on RubyGems?

**Comment by pietromenna** [comment]
The idea was for me to show you what needed to go into a Pull Request (tests, code and documentation). After we merge the code into the main repo we can release a new version.

Ideally, we can create similar test cases than the one in the example for the other features.

**Comment by dancinglightning** [comment]
Hi, i was just researching the topic and landed here. The method discussed works fine off course, but i would like to add something i noticed.
Wikipedia articles seem to have sections, and for long ones the first section is a summary and that is followed by the table of contents.
Sections seem delimited by  == XXXEdit == where XXX could be EarlyLife or Career. 
I think there is a point to be made for returning the first section as the summary. 
Or it could be  a separate function ? thoughts ?

**Comment by maurobio** [comment]
@dancinglightning That's precisely what my code above does. It looks for the first section eding with a "=" and grabs it as the article's summary. The code is not yet implemented as a method, but I expect to do it soon.

**Comment by dancinglightning** [comment]
@maurobio ok, great. Sorry i just skimped the code and didn't see the = in there. I'm not so good at regex. Might want to expand to == or even "== space word space ==" (whatever that is in regex)
Is this making a release soon ?

**Comment by pietromenna** [comment]
Hi @maurobio  & @dancinglightning,

I am releasing a new version with the changes with the summary method today.
