### ISSUE TITLE
the list of links is incomplete

### ISSUE THREAD

**Issue by nanowang** [kenpratt/wikipedia-client#59]
re-pro:

`Wikipedia.find( 'Getting Things Done' ).links`

output:

```
["Automatic transmission", "Ben Hammersley", "Business", "Cult following", "David Allen (author)", "Digital object identifier", "Distraction", "Distributed cognition", "Extended mind", "Francis Heylighen"]
```

expected:

should return the complete links, instead of the first 10 links.

**Comment by pietromenna** [comment]
Hi @nanowang ,

This is not a real issue with 'wikipedia' gem but how the wikipedia API works. For more details check this [link](https://www.mediawiki.org/wiki/API:Links). There you will find the text below:

> pllimit: How many links to return. No more than 500 (5000 for bots) allowed. (Default: 10)

Now, how you can make this work with the Gem:

`Wikipedia.find( 'Getting Things Done', :pllimit => 500 ).links `

Just note that anyway you cannot get more than 500 results. 

Hope this helps!

**Comment by nanowang** [comment]
Ah sorry, missed that in the docs. Thanks for the instruction!
