### ISSUE TITLE
page.links only gives 10 links

### ISSUE THREAD

**Issue by henrywoody** [kenpratt/wikipedia-client#63]
For example `Wikipedia.find('https://en.wikipedia.org/wiki/List_of_wars_before_1000').links #=> ["1st millennium", "1st millennium BC", "464 BC Sparta earthquake", "Abbasid Caliphate", "Abbasid Revolution", "Abd Allah ibn al-Zubayr", "Abi-Eshuh", "Acarnania", "Achaea (ancient region)", "Achaean League"] ` but there are probably hundreds of links on this page.

**Comment by henrywoody** [comment]
Okay so 10 is the default number set by Wikipedia, however the maximum for a user is 500. Is there a way to modify the number of links returned through this gem?

**Comment by pietromenna** [comment]
Hi @henrywoody . This is a duplicate of #59 . You can look the issue [here](https://github.com/kenpratt/wikipedia-client/issues/59).

`Wikipedia.find( 'Getting Things Done', :pllimit => 500 ).links`

I hope this helps.
