### ISSUE TITLE
Can't get a thumbnail from images 

### ISSUE THREAD

**Issue by TehraniX** [kenpratt/wikipedia-client#70]
Rather a feature request than an issue. If you call the Wikipedia API through

`https://en.wikipedia.org/w/api.php?action=query&titles=London&prop=pageimages&format=json&pilimit=5&pithumbsize=800`

you can get a thumbnail of the main image. In that case either width or height of the image has 800px.

The thumbnails can be very useful for images, which are too large, e.g. the main image of Munich. The following code only delivers the several MB sized image from Wikipedia:

```
  wikipedia_city_page = Wikipedia.find("München")
  @image_url = wikipedia_city_page.main_image_url
```
=> [Retrieved image URL of Munich](https://upload.wikimedia.org/wikipedia/commons/5/59/Munchen_collage.jpg)

It would be really great, if we could also get a thumbnail from that image through the wikipedia gem.

Thanks a lot!

**Comment by pietromenna** [comment]
Hi @TehraniX ,

Pull Request #71 added the functionality you requested. Thanks @panaak !

**Comment by TehraniX** [comment]
Thanks @pietromenna! @panaak, thanks for implementing the feature!

Will try it out.
