### ISSUE TITLE
Errors in Ruby 3.0.x and warnings in Ruby 2.7.x

### ISSUE THREAD

**Issue by DannyBen** [kenpratt/wikipedia-client#88]
## Problem

The gem seems to use deprecated and obsolete method calls on the `URI` module. 

## Reproduction code

Run this code in Ruby 2.7.3 or Ruby 3.0.1

```ruby
require 'wikipedia'
page = Wikipedia.find 'Getting Things Done'
```
## Actual behavior

**Ruby 2.7.3** - `URI.escape is obsolete` (warning)

```
.../gems/2.7.0/gems/wikipedia-client-1.12.0/lib/wikipedia/client.rb:109: warning: URI.escape is obsolete
```

**Ruby 3.0.1** - `undefined method encode for URI:Module (NoMethodError)` (fatal)

```
.../gems/3.0.0/gems/wikipedia-client-1.12.0/lib/wikipedia/client.rb:109:in `encode': undefined method `encode' for URI:Module (NoMethodError)
```

---

I see this was mentioned in https://github.com/kenpratt/wikipedia-client/commit/b9e4b4a19aa1c18b03b0b114fdcc062fae698635 but then reverted in https://github.com/kenpratt/wikipedia-client/commit/0adc083e558e55f81606949c7d53720786ef90a5 - which I believe was the right call, since `CGI.escape` is not a 1-to-1 replacement, but the problem still needs fixing.

**Comment by kenpratt** [comment]
Thanks for reporting, @DannyBen. There's some additional discussion in https://github.com/kenpratt/wikipedia-client/pull/84.

Yes, there are some non-trivial changes required for Ruby 3 support. The code in this gem that uses `URI.encode` and `URI.decode` is fairly complicated, it seems to be used in a number of ways that aren't very straightforward.

I'm not sure if/when I'll have time to fix this. If you or anyone stumbling across this thread is interested in giving it a shot, I'm very open to contributions!

**Comment by DannyBen** [comment]
Understood.

I believe the [Addressable](https://github.com/sporkmonger/addressable) gem can be used as a drop-in replacement, until (and if) someone wants to take a more specific take on the fix.

Would this be acceptable? if so, I might be able to take a stab at a PR.
