### ISSUE TITLE
Move away from travis-ci.org

### ISSUE THREAD

**Issue by DannyBen** [kenpratt/wikipedia-client#91]
travis-ci.org will be shut down soon. I suggest moving to Github Actions, or if for some reason, there is a desire to stay with travis, the account must be migrated to travis-ci.com.

If the move to Github Actions is a possibility, I don't mind implementing it.

**Comment by kenpratt** [comment]
No particular desire to stay on Travis. If you want to give a migration to Github Actions a shot, that would be appreciated!

**Comment by DannyBen** [comment]
Sure thing. I will tackle this after the currently open PRs are done.
